server:
  port: 8080
  servlet:
    session:
      timeout: 1800 #设置session的过期时间，单位是s
#    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/li_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-center
logging:
  level:
    root: info
    com.lixinghao.user.mapper: debug
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)